export interface Product {
  id: string;
  imageSrc: string;
  productName: string;
  price: number;
  isNew: boolean;
  isBestSeller: boolean;
  isHotPromo: boolean;
  isFavorite: boolean;
}

export const tshirtData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];

export const sweatshirtData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];

export const dressData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];

export const pantsandskirtData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];

export const sweaterData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];

export const stuffandaccesoriesData: Product[] = [
  {
    id: "1",
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "2",
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "3",
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "4",
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "5",
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "6",
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    id: "7",
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "8",
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    id: "9",
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];
