export const tShirtData = [
  {
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];



export const sweatshirtData = [
  {
    imageSrc: "/ecommerce/item-1.jpg",
    productName: "Product 1",
    price: 100,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-2.jpg",
    productName: "Product 2",
    price: 150,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-3.jpg",
    productName: "Product 3",
    price: 200,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-4.jpg",
    productName: "Product 4",
    price: 250,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-5.jpg",
    productName: "Product 5",
    price: 300,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-6.jpg",
    productName: "Product 6",
    price: 350,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-7.jpg",
    productName: "Product 7",
    price: 400,
    isNew: true,
    isBestSeller: false,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-8.jpg",
    productName: "Product 8",
    price: 450,
    isNew: false,
    isBestSeller: true,
    isHotPromo: false,
    isFavorite: true,
  },
  {
    imageSrc: "/ecommerce/item-9.jpg",
    productName: "Product 9",
    price: 500,
    isNew: false,
    isBestSeller: false,
    isHotPromo: true,
    isFavorite: true,
  },
];
